"""Write sage/prompts.py from the live skill files via sage.skill_loader.

The loader is the single source of truth; this script writes a committed
snapshot so production (where `.claude/` isn't shipped) has a working
`SYSTEM_PROMPT` to import.

Usage:
    python scripts/build_prompts.py

CI mode (exit 1 if sage/prompts.py would change):
    python scripts/build_prompts.py --check
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "sage" / "prompts.py"

sys.path.insert(0, str(ROOT))
from sage.skill_loader import build_system_prompt  # noqa: E402


def render_file(body: str) -> str:
    return (
        '"""SAGE system prompt — AUTO-GENERATED by scripts/build_prompts.py.\n'
        "\n"
        "DO NOT EDIT DIRECTLY. Edit the prompt-contribution blocks in CLAUDE.md\n"
        "and .claude/skills/*/SKILL.md, then run: python scripts/build_prompts.py\n"
        '"""\n'
        "\n"
        'SYSTEM_PROMPT = """\\\n'
        f"{body}\n"
        '"""\n'
    )


def main(argv: list[str]) -> int:
    check = "--check" in argv
    body = build_system_prompt(ROOT)
    if body is None:
        print(
            f"ERROR: {ROOT / '.claude' / 'skills'} not found — cannot build prompt.",
            file=sys.stderr,
        )
        return 1
    new = render_file(body)

    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != new:
            print(
                f"ERROR: {OUTPUT.relative_to(ROOT)} is out of sync with "
                "source skills. Run: python scripts/build_prompts.py",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {OUTPUT.relative_to(ROOT)} is in sync")
        return 0

    OUTPUT.write_text(new, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(new)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
