"""Generate sage/prompts.py from CLAUDE.md + selected .claude/skills/*/SKILL.md.

Reads <!-- prompt-contribution:start --> ... <!-- prompt-contribution:end -->
blocks from each source file (in the order defined below) and concatenates
them into a single SYSTEM_PROMPT string literal.

Safe by design: stdlib only, no network, no env vars, no shelling out. Run it
before committing changes to CLAUDE.md or any skill with a contribution block.

Usage:
    python scripts/build_prompts.py

CI mode (exit 1 if sage/prompts.py would change):
    python scripts/build_prompts.py --check
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / ".claude" / "skills"
CLAUDE_MD = ROOT / "CLAUDE.md"
OUTPUT = ROOT / "sage" / "prompts.py"

SOURCES: list[Path] = [
    CLAUDE_MD,
    SKILLS / "session-router" / "SKILL.md",
    SKILLS / "onboarding" / "SKILL.md",
    SKILLS / "scenario-runner" / "SKILL.md",
    SKILLS / "improve-interaction" / "SKILL.md",
    SKILLS / "weekly-review" / "SKILL.md",
    SKILLS / "prompt-coaching" / "SKILL.md",
    SKILLS / "reflection-facilitator" / "SKILL.md",
    SKILLS / "level-classifier" / "SKILL.md",
    SKILLS / "skill-evaluator" / "SKILL.md",
]

BLOCK_RE = re.compile(
    r"<!--\s*prompt-contribution:start\s*-->\s*\n(.*?)\n\s*<!--\s*prompt-contribution:end\s*-->",
    re.DOTALL,
)


def extract_blocks(path: Path) -> list[str]:
    if not path.exists():
        print(f"warn: {path.relative_to(ROOT)} not found, skipping", file=sys.stderr)
        return []
    text = path.read_text(encoding="utf-8")
    return [m.group(1).strip() for m in BLOCK_RE.finditer(text)]


def build_prompt() -> str:
    sections: list[str] = []
    for src in SOURCES:
        sections.extend(extract_blocks(src))
    body = "\n\n".join(sections)
    if '"""' in body:
        raise SystemExit(
            "ERROR: extracted content contains triple quotes — refusing to "
            "write a malformed Python literal. Remove or escape them in the "
            "source skill/CLAUDE.md."
        )
    return body


def render_file(body: str) -> str:
    return (
        '"""SAGE system prompt — AUTO-GENERATED by scripts/build_prompts.py.\n'
        "\n"
        "DO NOT EDIT DIRECTLY. Edit the prompt-contribution blocks in CLAUDE.md\n"
        "and .claude/skills/*/SKILL.md, then run: python scripts/build_prompts.py\n"
        '"""\n'
        "\n"
        'SYSTEM_PROMPT = """\\\n'
        f"{body}\n"
        '"""\n'
    )


def main(argv: list[str]) -> int:
    check = "--check" in argv
    new = render_file(build_prompt())

    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != new:
            print(
                f"ERROR: {OUTPUT.relative_to(ROOT)} is out of sync with "
                "source skills. Run: python scripts/build_prompts.py",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {OUTPUT.relative_to(ROOT)} is in sync")
        return 0

    OUTPUT.write_text(new, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(new)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
